Repository IET-DAVV/website-client, pull requests merged in 2022-11, with the labels that each got.

#27 [Feat]: Added folder structure and created file
  CONTRIBUTIONS.md
Labels: documentation, enhancement

#35 [Fix]: Add assignees -> false
  .github/auto_assign.yml
Labels: bug

#40 Update CONTRIBUTIONS.md
  CONTRIBUTIONS.md
Labels: documentation, enhancement

#42 [Feat]: Prettierrc, eslintrc added
  .eslintrc.json
  .prettierrc
  components/Loader/Loader.tsx
  package-lock.json
  package.json
  pages/index.tsx
Labels: enhancement, config

#43 Basic Button Added
  .prettierrc
  components/Button/Button.module.scss
  components/Button/index.tsx
  components/index.ts
  components/interfaces.ts
  next.config.js
  package-lock.json
  package.json
  pages/Home.module.scss
  pages/index.tsx
Labels: enhancement

#44 [Fix]: Added contribution file link in greetings message gh
  .github/workflows/greetings.yml
Labels: bug, review-requested👀

#54 [Feat]: .vscode added
  .vscode/settings.json
Labels: enhancement, config

#57 [Feat]: Storybook Added
  .eslintrc.json
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  assets/icons/discord.svg
  assets/index.tsx
  components/BaseTemplate/BaseTemplate.mocks.tsx
  components/BaseTemplate/BaseTemplate.module.scss
  components/BaseTemplate/BaseTemplate.stories.tsx
  components/BaseTemplate/index.tsx
  components/Buttons/Button/Button.mocks.tsx
  components/Buttons/Button/Button.module.scss
  components/Buttons/Button/Button.stories.tsx
  components/Buttons/Button/index.tsx
  components/Buttons/IconButton/IconButton.mocks.tsx
  components/Buttons/IconButton/IconButton.module.scss
  components/Buttons/IconButton/IconButton.stories.tsx
  components/Buttons/IconButton/index.tsx
  components/Buttons/index.ts
  components/Buttons/interfaces.ts
  components/Buttons/utils.ts
  components/Card/index.tsx
  components/Loader/Loader.tsx
  components/Loader/index.tsx
  components/Modal/index.tsx
  components/TextField/index.tsx
  components/index.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  utils/contexts/GlobalContext.tsx
  utils/index.ts
Labels: enhancement, review-requested👀

#62 [Feat]: Create eslint workflow for PRs
  .github/workflows/eslint.yml
Labels: enhancement, config
